# serverless.yml

service: serverless-flask

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  environment:
    BASE_PATH: 'poc'

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  customDomain:
    domainName: 'api.magerabis.com'
    basePath: ${self:provider.environment.BASE_PATH}
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  app:
    handler: wsgi_handler.handler
    package: {}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'